# Generated by Django 3.2.5 on 2021-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
