site_name: bills
site_description: an App for manage customers bills
repo_url: https://github.com/djv/bills
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/djv">djv</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
