# Generated by Django 3.2.5 on 2021-07-27 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsitems',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billsapi.bills'),
        ),
    ]
