# Generated by Django 3.2.5 on 2021-08-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsapi', '0005_billsitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsitems',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
