# Generated by Django 3.2.5 on 2021-07-31 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsapi', '0002_alter_billsitems_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsitems',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='billsitems',
            name='valid',
        ),
    ]
